services:
    nginx:
      build: ./nginx
      container_name: nginxcont
      ports:
        - "80:8080"
    fcgi:
      build: ./fcgi
      container_name: fcgicont
      ports:
        - "8080:8080"
